fragment Device on Device {
  id
  deviceId
  firstSeenAt
  lastUploadAt
  segmentsFrom
}

fragment Point on Point {
  id
  clientId
  deviceId
  ts
  lat
  lon
  acc
  speed
  heading
  alt
}

fragment Place on Place {
  id
  clientId
  name
  lat
  lon
  radius
  updatedAt
  deletedAt
}

fragment Visit on Visit {
  id
  clientId
  deviceId
  start
  end
  lat
  lon
  radius
  pointCount
  placeClientId
  duration
}

fragment Trip on Trip {
  id
  clientId
  deviceId
  start
  end
  fromVisit
  toVisit
  distance
  mode
  duration
}

fragment ChangeSet on ChangeSet {
  points {
    ...Point
  }
  visits {
    ...Visit
  }
  trips {
    ...Trip
  }
  places {
    ...Place
  }
  deletedPlaces
  nextCursor
  hasMore
}
